require_relative 'ship'
require_relative 'carrier'
require_relative 'battleship'
require_relative 'cruiser'
require_relative 'destroyer'
require_relative 'submarine'
require_relative 'board.rb'
require_relative "converter"

placing_board = Board.new
ship_classes = [Carrier, Battleship, Cruiser, Destroyer, Submarine]


#array of ship instances generated by user
ship_instances = {}
# entry of ships locations into each ship instance
ship_classes.each do |ship_class|
  ship = ship_class.new
  ship.size.times do |iteration|
    puts "\e[H\e[2J"
    puts "************************"
    puts "    --BATTLESHIP--\n"
    puts "************************\n\n"

    puts "STEP 1: LOCATE YOUR SHIPS\n"
    puts "--------------------------\n\n"

    puts placing_board.print_state
    puts "#{ship.class.to_s.upcase}:\n"
    puts "**********\n"
    puts "Enter where in the board you want to locate your #{ship.class} (it has a size of #{ship.size})."
    puts "#{ship.size - iteration} more entries to go (enter them one by one, i.e, A7):"
    placing = gets.chomp
    ship.locations << placing
    coordinates = Converter.convert(placing)
    placing_board.mark_placing(coordinates)
    puts placing_board.print_state
  end
  puts "\nYour #{ship.class} has the following position: #{ship.locations}\n\n"
  # store the new ship with user entered locations
  key = ship.class.to_s.downcase.to_sym
  ship_instances[key] = ship
end
# generate board instance with all the ship instances
board = Board.new(ship_instances)



# clear terminal;
puts "\e[H\e[2J"
puts board.ships

puts placing_board.print_state
puts "\n\nThis is the final board, set up by Player 1 - Player 2, prepare to start! (Press enter to continue):"

start = gets.chomp


# play the game

until board.ships.empty?
  puts "\e[H\e[2J"
  puts "************************"
  puts "    --BATTLESHIP--\n"
  puts "************************\n\n"

  puts "STEP 2: PLAY\n"
  puts "--------------\n\n"
  puts board.print_state
  puts "Player 2: Enter location you want to fire at:"
  target = gets.chomp

  target_coordinates = Converter.convert(target)
  # fire at the board
  if board.fire(target)
    puts "You hit something!"
    board.mark_hit(target_coordinates)
    if board.scan
      puts "You sunk a ship!"
    end
  else
    puts "You missed..."
    board.mark_miss(target_coordinates)
  end

  puts "Press enter to refresh board:"
  start = gets.chomp

end



#
